In [9]:
import numpy as np
%time

# Part 1
python_list = list(range(100000))
numpy_array = np.array(python_list)
start = time.time()
[x * 5 for x in python_list]
end = time.time()
list_time = end - start
start = time.time()
numpy_array * 5
end = time.time()
numpy_time = end - start
print("List time:", list_time)
print("NumPy time:", numpy_time)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.01 µs
List time: 0.008397579193115234
NumPy time: 0.00046062469482421875


In [10]:
 #Part2
 %time

arr1 = np.arange(1, 11)
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr1.ndim, arr1.shape, arr1.size, arr1.dtype, arr1.itemsize)
print(arr2.ndim, arr2.shape, arr2.size, arr2.dtype, arr2.itemsize)
float_arr = np.random.rand(3, 3)
int_arr = float_arr.astype(int)
print(float_arr, int_arr)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.01 µs
1 (10,) 10 int64 8
2 (3, 3) 9 int64 8
[[0.32051364 0.76934693 0.65317875]
 [0.26922984 0.68129965 0.38805526]
 [0.2131438  0.31089837 0.83640259]] [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
# Part 3
%time
zero_matrix = np.zeros((4, 4))
one_matrix = np.ones((3, 2))
identity_matrix = np.eye(5)
const_array = np.full((3, 3), 7)
rand_array = np.random.randint(10, 100, (3, 4))
arange_arr = np.arange(5, 50, 5).reshape(3, 3)
print(zero_matrix, one_matrix, identity_matrix, const_array, rand_array, arange_arr)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.77 µs
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1.]
 [1. 1.]
 [1. 1.]] [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] [[7 7 7]
 [7 7 7]
 [7 7 7]] [[13 24 89 82]
 [63 42 26 51]
 [96 91 31 12]] [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [12]:
# Part 4: Indexing and Slicing
%time
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
print(arr[1])
print(arr[:2, 1:3])
print(arr[:, 3])
arr[1] = [1, 2, 3, 4]
print(arr)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.44 µs
[50 60 70 80]
[[20 30]
 [60 70]]
[ 40  80 120]
[[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]


In [13]:
# Part 4: Vectorization
%time
A = np.random.randint(1, 100, 5)
B = np.random.randint(1, 100, 5)
print(A + B, A - B, A * B, A / B)
C = np.array([1, 2, 3, 4, 5])
print(np.sqrt(C), np.exp(C), np.sin(C))
temperatures = np.array([20, 25, 30, 35, 40, 15, 10, 5, 0, -5])
fahrenheit = (temperatures * 9/5) + 32
print(fahrenheit)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.01 µs
[ 84  79  42  87 100] [  0  -9  40 -31 -16] [1764 1540   41 1652 2436] [ 1.          0.79545455 41.          0.47457627  0.72413793]
[1.         1.41421356 1.73205081 2.         2.23606798] [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ] [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 68.  77.  86.  95. 104.  59.  50.  41.  32.  23.]


In [14]:
# Part 4: Broadcasting
%time
A = np.arange(1, 10).reshape(3, 3)
print(A + 10)
print(A + np.array([1, 2, 3]))
print(A + np.array([[1], [2], [3]]))

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.29 µs
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [15]:
# Part 4: Reshape, Flatten, Ravel
%time
arr = np.arange(1, 13)
reshaped1 = arr.reshape(3, 4)
reshaped2 = arr.reshape(2, 6)
flat = reshaped1.flatten()
ravel_arr = reshaped1.ravel()
flat[0] = 99
ravel_arr[1] = 88
print(reshaped1, reshaped2, flat, ravel_arr, reshaped1)
arr2 = np.arange(1, 10).reshape(3, 3)
flat2 = arr2.flatten()
ravel2 = arr2.ravel()
ravel2[0] = 77
print(flat2, ravel2, arr2)


CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.77 µs
[[ 1 88  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] [[ 1 88  3  4  5  6]
 [ 7  8  9 10 11 12]] [99  2  3  4  5  6  7  8  9 10 11 12] [ 1 88  3  4  5  6  7  8  9 10 11 12] [[ 1 88  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4 5 6 7 8 9] [77  2  3  4  5  6  7  8  9] [[77  2  3]
 [ 4  5  6]
 [ 7  8  9]]
